services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:4.4.3
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: